import { Meta, StoryObj } from '@storybook/react';
import { EventRow } from './EventRow';
declare const meta: Meta<typeof EventRow>;
export default meta;
type Story = StoryObj<typeof EventRow>;
export declare const FeaturedOnly: Story;
export declare const FeaturedAndOthers: Story;
export declare const NoFeaturedOffers: Story;
export declare const SoldOut: Story;
export declare const ComingSoon: Story;
export declare const AllStates: Story;
