import {createClient} from '@sanity/client'
import dotenv from 'dotenv'

// Load environment variables
dotenv.config()

// Initialize Sanity client with write token
const client = createClient({
  projectId: process.env.SANITY_PROJECT_ID,
  dataset: process.env.SANITY_DATASET || 'production',
  useCdn: false,
  apiVersion: '2024-01-01',
  token: process.env.SANITY_WRITE_TOKEN, // You'll need to set this in .env
})

const teams = [
  {
    _id: 'wolves',
    _type: 'team',
    name: 'Minnesota Timberwolves',
    shortName: 'Timberwolves',
    city: 'Minneapolis',
    sport: 'NBA',
    teamId: {_type: 'slug', current: 'wolves'},
    brandColors: {
      core: '#266092',
      light: '#79BC43',
      dark: '#0C233F',
      darkSurface: '#0C233F',
      interactive: '#266092',
      inverted: '#79BC43',
      lightBase: '#FFFFFF',
      lightSurface: '#EEF2F6',
      lightTransactional: '#266092',
      lightPrimaryBtn: '#266092',
      darkTransactional: '#79BC43',
      darkPrimaryBtn: '#FFFFFF',
    },
    buttonRadius: '8px',
    displayFont: 'Inter',
  },
  {
    _id: 'lynx',
    _type: 'team',
    name: 'Minnesota Lynx',
    shortName: 'Lynx',
    city: 'Minneapolis',
    sport: 'WNBA',
    teamId: {_type: 'slug', current: 'lynx'},
    brandColors: {
      core: '#266092',
      light: '#79BC43',
      dark: '#0C233F',
      darkSurface: '#0C233F',
      interactive: '#266092',
      inverted: '#79BC43',
      lightBase: '#FFFFFF',
      lightSurface: '#EEF2F6',
      lightTransactional: '#266092',
      lightPrimaryBtn: '#266092',
      darkTransactional: '#79BC43',
      darkPrimaryBtn: '#FFFFFF',
    },
    buttonRadius: '12px',
    displayFont: 'Inter',
  },
  {
    _id: 'courage',
    _type: 'team',
    name: 'North Carolina Courage',
    shortName: 'Courage',
    city: 'Cary',
    sport: 'NWSL',
    teamId: {_type: 'slug', current: 'courage'},
    brandColors: {
      core: '#AB0033',
      light: '#B4A269',
      dark: '#001420',
      darkSurface: '#142631',
      interactive: '#AB0033',
      inverted: '#B4A269',
      lightBase: '#FFFFFF',
      lightSurface: '#F4F4F4',
      lightTransactional: '#AB0033',
      lightPrimaryBtn: '#AB0033',
      darkTransactional: '#B4A269',
      darkPrimaryBtn: '#B4A269',
    },
    buttonRadius: '100px',
    displayFont: 'Inter',
  },
  {
    _id: 'summit',
    _type: 'team',
    name: 'Denver Summit FC',
    shortName: 'Summit FC',
    city: 'Denver',
    sport: 'MLS',
    teamId: {_type: 'slug', current: 'summit'},
    brandColors: {
      core: '#20604E',
      light: '#C04D38',
      dark: '#262628',
      darkSurface: '#262628',
      interactive: '#20604E',
      inverted: '#E6B93F',
      lightBase: '#FFFFFF',
      lightSurface: '#F4F4F4',
      lightTransactional: '#20604E',
      lightPrimaryBtn: '#20604E',
      darkTransactional: '#E6B93F',
      darkPrimaryBtn: '#E6B93F',
    },
    buttonRadius: '8px',
    displayFont: 'Inter',
  },
  {
    _id: 'bucknell',
    _type: 'team',
    name: 'Bucknell Bison',
    shortName: 'Bison',
    city: 'Lewisburg',
    sport: 'NCAA',
    teamId: {_type: 'slug', current: 'bucknell'},
    brandColors: {
      core: '#003865',
      light: '#E87722',
      dark: '#141414',
      darkSurface: '#292929',
      interactive: '#003865',
      inverted: '#E87722',
      lightBase: '#FFFFFF',
      lightSurface: '#F4F4F4',
      lightTransactional: '#003865',
      lightPrimaryBtn: '#003865',
      darkTransactional: '#E87722',
      darkPrimaryBtn: '#E87722',
    },
    buttonRadius: '100px',
    displayFont: 'Inter',
  },
  {
    _id: 'sounders',
    _type: 'team',
    name: 'Seattle Sounders FC',
    shortName: 'Sounders',
    city: 'Seattle',
    sport: 'MLS',
    teamId: {_type: 'slug', current: 'sounders'},
    brandColors: {
      core: '#004B2D',
      light: '#5BB6E5',
      dark: '#001A0F',
      darkSurface: '#292929',
      interactive: '#004B2D',
      inverted: '#5BB6E5',
      lightBase: '#FFFFFF',
      lightSurface: '#F4F4F4',
      lightTransactional: '#004B2D',
      lightPrimaryBtn: '#004B2D',
      darkTransactional: '#5BB6E5',
      darkPrimaryBtn: '#5BB6E5',
    },
    buttonRadius: '100px',
    displayFont: 'Inter',
  },
  {
    _id: 'reign',
    _type: 'team',
    name: 'Seattle Reign FC',
    shortName: 'Reign',
    city: 'Seattle',
    sport: 'NWSL',
    teamId: {_type: 'slug', current: 'reign'},
    brandColors: {
      core: '#5B2C8D',
      light: '#C6A84B',
      dark: '#1A0A2E',
      darkSurface: '#292929',
      interactive: '#5B2C8D',
      inverted: '#C6A84B',
      lightBase: '#FFFFFF',
      lightSurface: '#F4F4F4',
      lightTransactional: '#5B2C8D',
      lightPrimaryBtn: '#5B2C8D',
      darkTransactional: '#C6A84B',
      darkPrimaryBtn: '#C6A84B',
    },
    buttonRadius: '100px',
    displayFont: 'Inter',
  },
  {
    _id: 'ncfc',
    _type: 'team',
    name: 'North Carolina FC',
    shortName: 'NCFC',
    city: 'Cary',
    sport: 'MLS',
    teamId: {_type: 'slug', current: 'ncfc'},
    brandColors: {
      core: '#00416B',
      light: '#C8A84B',
      dark: '#001A2E',
      darkSurface: '#292929',
      interactive: '#00416B',
      inverted: '#C8A84B',
      lightBase: '#FFFFFF',
      lightSurface: '#F4F4F4',
      lightTransactional: '#00416B',
      lightPrimaryBtn: '#00416B',
      darkTransactional: '#C8A84B',
      darkPrimaryBtn: '#C8A84B',
    },
    buttonRadius: '100px',
    displayFont: 'Inter',
  },
  {
    _id: 'jump',
    _type: 'team',
    name: 'JUMP',
    shortName: 'JUMP',
    city: 'San Francisco',
    sport: 'NBA',
    teamId: {_type: 'slug', current: 'jump'},
    brandColors: {
      core: '#657DFF',
      light: '#CCFF00',
      dark: '#131939',
      darkSurface: '#292929',
      interactive: '#4C65F0',
      inverted: '#CCFF00',
      lightBase: '#FFFFFF',
      lightSurface: '#F4F4F4',
      lightTransactional: '#4C65F0',
      lightPrimaryBtn: '#4C65F0',
      darkTransactional: '#CCFF00',
      darkPrimaryBtn: '#CCFF00',
    },
    buttonRadius: '100px',
    displayFont: 'Inter',
  },
  {
    _id: 'athletics',
    _type: 'team',
    name: 'Oakland Athletics',
    shortName: 'Athletics',
    city: 'Oakland',
    sport: 'MLB',
    teamId: {_type: 'slug', current: 'athletics'},
    brandColors: {
      core: '#006141',
      light: '#FFB819',
      dark: '#051715',
      darkSurface: '#292929',
      interactive: '#006141',
      inverted: '#FFB819',
      lightBase: '#FFFFFF',
      lightSurface: '#F4F4F4',
      lightTransactional: '#006141',
      lightPrimaryBtn: '#006141',
      darkTransactional: '#FFB819',
      darkPrimaryBtn: '#FFB819',
    },
    buttonRadius: '100px',
    displayFont: 'Inter',
  },
]

async function importTeams() {
  try {
    console.log('Importing teams to Sanity...')

    for (const team of teams) {
      console.log(`  Importing ${team.name}...`)
      await client.createOrReplace(team)
    }

    console.log('✅ All teams imported successfully!')
  } catch (error) {
    console.error('Error importing teams:', error)
    process.exit(1)
  }
}

importTeams()
